# Generated by Django 3.2.15 on 2022-09-11 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("name", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Subjects",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                ("name", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("description", models.TextField()),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="field", to="entries.subject"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Fields",
                "ordering": ("name",),
                "unique_together": {("name", "subject")},
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public", models.BooleanField(default=False)),
                ("text", models.TextField()),
                ("nouns", models.JSONField(blank=True, default=list)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="entry", to="entries.field"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="entry", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Entries",
                "ordering": ("date",),
            },
        ),
    ]
