# Generated by Django 3.2.15 on 2022-09-12 20:21

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taggit", "0005_auto_20220424_2025"),
        ("entries", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entry",
            name="nouns",
        ),
        migrations.AddField(
            model_name="entry",
            name="nouns",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
